### PR TITLE
Preparing Tupl for publishing in the nexus maven repository

### PR DESCRIPTION
**Pull request by avshabanov**
This prepares Tupl for publishing in the nexus maven repository.

Note, that you should have a valid gpg key for signing your artifacts (of course you also need to install gpg2 on the computer you're going to use to release artifacts). After installing a key your ``~/.gnupg`` directory may look as follows:

```
$ ls ~/.gnupg/
gpg.conf	pubring.gpg	secring.gpg	trustdb.gpg
```

Also you need to modify your ``~/.m2/settings.xml`` a bit. This is important as it tells release plugin that you're going to release this to ``ossrh`` repository (note, that ossrh is also referenced in ``pom.xml``).

This is how it can look like (I'm copying mine with asterisks instead of passwords):

```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
  http://maven.apache.org/xsd/settings-1.0.0.xsd">

  <!--
      See http://central.sonatype.org/pages/apache-maven.html and 
      http://maven.apache.org/guides/mini/guide-encryption.html and
      https://maven.apache.org/settings.html
  -->

  <servers>
    <server>
      <id>ossrh</id>
      <username>YOUR_USERNAME</username>
      <password>*</password>
    </server>
  </servers>

  <profiles>
    <profile>
      <id>ossrh</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <gpg.executable>gpg2</gpg.executable>
        <gpg.passphrase>*</gpg.passphrase>
      </properties>
    </profile>
  </profiles>
</settings>
```

You don't need to have gpg2 installed for any non-release work. The signing step (as well as attaching sources and generating javadoc) is performed only when 'release' profile is activated.

Feel free to ask if you have any questions related to maven.

### CODE REVIEW

**Comment by broneill** [comment]
I tried to run the release process, but maven just complains: 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5:prepare (default-cli) on project tupl: Failed to invoke Maven build. Error configuring command-line. Reason: Maven executable not found at: C:\apps\apache-maven-3.3.3\bin\mvn.bat -> [Help 1]

Maven is installed correctly and is on the path.

mvn -v

Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T04:57:37-07:00)
Maven home: c:\apps\apache-maven-3.3.3\bin\..
Java version: 1.8.0_51, vendor: Oracle Corporation
Java home: c:\apps\jdk1.8\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "dos"

**Comment by avshabanov** [comment]
Looks like an issue of windows maven distribution (never had something like that on Mac or Linux) - http://stackoverflow.com/questions/29755620/failed-to-execute-goal-maven-releaseprepare

Possible solutions: copy mvn.bat to mvn.cmd or upgrade release plugin to 2.5.2 - https://issues.apache.org/jira/browse/MRELEASE-902

**Comment by broneill** [comment]
Still having issues:

[INFO] Checking in modified POMs...
[INFO] Executing: cmd.exe /X /C "git add -- pom.xml"
[INFO] Working directory: C:\Projects\Tupl
[INFO] Executing: cmd.exe /X /C "git rev-parse --show-toplevel"
[INFO] Working directory: C:\Projects\Tupl
[INFO] Executing: cmd.exe /X /C "git status --porcelain ."
[INFO] Working directory: C:\Projects\Tupl
[WARNING] Ignoring unrecognized line: ?? pom.xml.releaseBackup
[WARNING] Ignoring unrecognized line: ?? release.properties
[INFO] Executing: cmd.exe /X /C "git commit --verbose -F c:\temp\maven-scm-391255366.commit pom.xml"
[INFO] Working directory: C:\Projects\Tupl
[INFO] Executing: cmd.exe /X /C "git symbolic-ref HEAD"
[INFO] Working directory: C:\Projects\Tupl
[INFO] Executing: cmd.exe /X /C "git push git@github.com:cojen/Tupl.git refs/heads/master:refs/heads/master"
[INFO] Working directory: C:\Projects\Tupl
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11:37 min
[INFO] Finished at: 2015-09-19T17:30:19-07:00
[INFO] Final Memory: 16M/178M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.2:prepare (default-cli) on project tupl: Unable to commit files
[ERROR] Provider message:
[ERROR] The git-push command failed.
[ERROR] Command output:
[ERROR] warning: CRLF will be replaced by LF in pom.xml.
[ERROR] The file will have its original line endings in your working directory.
[ERROR] warning: CRLF will be replaced by LF in pom.xml.
[ERROR] The file will have its original line endings in your working directory.
[ERROR] warning: CRLF will be replaced by LF in pom.xml.
[ERROR] The file will have its original line endings in your working directory.
[ERROR] warning: CRLF will be replaced by LF in pom.xml.
[ERROR] The file will have its original line endings in your working directory.
[ERROR] Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
[ERROR] Permission denied (publickey).
[ERROR] fatal: Could not read from remote repository.
[ERROR]
[ERROR] Please make sure you have the correct access rights
[ERROR] and the repository exists.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by avshabanov** [comment]
Hmm
Stacktrace says that git-push failed. May be
* (VERY LIKELY) You are using http link while working with git (i.e. you used git clone https://github.com/cojen/Tupl.git when you cloned Tupl to your computer). You should either use ssh link (note the scm link in Tupl/pom.xml) - or - you should change that link in pom.xml to the one containing https://github.com/cojen/Tupl.git. I never did the latter though. I always used ssh links and I had a public/private key which were accessible by git.
* (unlikely, but also worth trying) try to changing CRLF to LF endings in Tupl sources.

**Comment by broneill** [comment]
It doesn't like it was cloned with https. The problem is that I use a variety of tools, and the 'git' command doesn't appear to be set up with the keys. I usually use TortoiseGit, and it sets things up differently.

Is there any reason why the release command must do the push itself?

**Comment by avshabanov** [comment]
Yes. Release plugin commits changes (that contain new snapshot version) along with a new tag to the repo. The tag points to the sources where pom.xml contains release version.
This is how things work by default. I personally find it very convenient.
As a workaround I may suggest to run release on separate host (e.g aws micro instance) where you would have the bare minimum required for making a release and have your custom desktop configuration intact.

**Comment by avshabanov** [comment]
Of course you can do that on local machine in virtualbox or the like. Aws micro instance is just an example. But probably there is a way to do that even on your custom configuration. Unfortunately I don't know how is it different from mine, not sure what would work better for you.

**Comment by broneill** [comment]
The release also runs all the tests, which takes about 10 minutes on my desktop. A micro instance will take several hours. Regardless, I'd like the project to remain platform agnostic, and so making it work on Windows is desirable. I just need to finish configuring git.

Considering that the release process requires two commands, I'm surprised that the first attempts to do something destructive -- push. I thought the first would prepare everything for inspection, and then the second would push to GitHub and Maven Central.

**Comment by avshabanov** [comment]
Hmm, I also thought push happens only on second phase (release:perform). I believe first phase is reversible - it just creates a bunch of property files. I can take another look into it when I'll be near my desktop again.

**Comment by avshabanov** [comment]
BTW, you can speed up release a little by skipping tests. I believe you just need to pass '-DskipTests=true' along with the other mvn arguments.

**Comment by broneill** [comment]
I've also noticed that the javadocs aren't generating properly anymore with the pom changes. I don't want to do a release to see what the javadocs look like.

**Comment by avshabanov** [comment]
You should be able to run javadoc plugin if you specify release profile, you don't need to necessarily specify release target when release profile is activated. I can also take a look into that when I'll be back to my computer (now replying from phone)

**Comment by broneill** [comment]
The problem is that the pom now contains profiles, and the default javadoc config isn't what I want.

**Comment by avshabanov** [comment]
You don't in fact need profiles. I find release profile to be convenient, but if it is not so - you can remove release profile and move definitions from it outside, so that javadoc will be available by default. Javadoc configuration is totally irrelevant to the release process. It's up to you to configure it. The only requirement is to post javadoc jar along with the main and source jars.

**Comment by avshabanov** [comment]
Just tried mvn javadoc:javadoc -Prelease on master HEAD - everything works with this change:

```
$ git diff
diff --git a/pom.xml b/pom.xml
index 7435795..c21706a 100644
--- a/pom.xml
+++ b/pom.xml
@@ -177,6 +177,7 @@
             <configuration>
               <javadocVersion>1.7</javadocVersion>
               <detectJavaApiLink>true</detectJavaApiLink>
+              <additionalparam>-Xdoclint:none</additionalparam>
               <links>
                 <link>http://docs.oracle.com/javase/7/docs/api</link>
               </links>
```

Also if you dislike profiles for some reason you can remove release profile and move everything to the standard scope.

**Comment by broneill** [comment]
I decided to have another go at this today. Given that Maven pushes to GitHub in the "prepare" step, and that uploading to the sonatype thingy is such a pain, I'm not going to bother with this again. I might start searching for a simple build/release system that doesn't suck so hard as Maven.

...
[INFO] Uploaded: https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/orgcojen-1006/org/cojen/tupl/1.2.7/tupl-1.2.7-sources.jar.asc (484 B at 3.9 KB/sec)
[INFO] [INFO]  * Upload of locally staged artifacts finished.
[INFO] [INFO]  * Closing staging repository with ID "orgcojen-1006".
[INFO]
[INFO] Waiting for operation to complete........
[INFO]
[INFO] [ERROR] Rule failure while trying to close staging repository with ID "orgcojen-1006".
[INFO] [ERROR]
[INFO] [ERROR] Nexus Staging Rules Failure Report
[INFO] [ERROR] ==================================
[INFO] [ERROR]
[INFO] [ERROR] Repository "orgcojen-1006" failures
[INFO] [ERROR]   Rule "signature-staging" failures
[INFO] [ERROR]     * No public key: Key with id: (c9079ad959bab95f) was not able to be located on &lt;a href=http://keyserver.ubuntu.com:11371&gt;http://keyserver.ubuntu.com:11371&lt;/a&gt;. Upload your public key and try the operation again.
...

Why in the world is it asking me to install a public key at ubuntu.com?

**Comment by avshabanov** [comment]
Hmm, it looks like some kind of misconfiguration - it shouldn't publish anything on prepare step.
WRT public keys - maven uses public sources where it expects to find your public key (to authenticate you as a publisher). I guess ubuntu keyserver is one of the many mirrors where people publish their public keys.

Given the amount of pain you had to come through - I'm sorry for suggesting you to follow this way.

Do you mind if I fork your repo and publish it to the maven myself? It will be published in com.truward groupId (this is what I registered for my opensource maven publications).

From time to time I will pull sources from your master repo and publish new versions (when I have time).

**Comment by broneill** [comment]
Go for it.

**Comment by avshabanov** [comment]
Did this: http://search.maven.org/#artifactdetails%7Ccom.truward.tupl%7Ctupl%7C1.2.18%7Cpom
https://github.com/truward/Tupl

**Pull request merged**
