### PR TITLE
Minor Grammar Changes in README.md

### PR DESCRIPTION
**Pull request by jakemcf22**
- powerful enough for supporting -> powerful enough to support
- Reworked a sentence so that it doesn't start with "because"

### CODE REVIEW

**Comment by broneill** [comment]
The changes seem fine to me. I notice that you've recently created a bunch of grammar fix PRs for several other projects. What's the reason for doing this? The projects are all unrelated. Are you testing a bot of some kind?

**Comment by jakemcf22** [comment]
Nothing as interesting as that unfortunately. I have to get a bunch of pull requests for documentation committed for an assignment

**Comment by broneill** [comment]
What kind of assignment is this? I don't particularly like being part of it.

**Comment by jakemcf22** [comment]
I just have to make edits to technical writing documents and provide a screenshot that they were approved. I can blur out your name and the name of the project if you would like.

**Comment by broneill** [comment]
If you're willing to blur out the name of the project, then any project will do. Pick another one, sorry.

**Pull request closed without merging**
